In [3]:
import numpy as np
from scipy import linalg

![picture 1](49f32bf910fcc368eacb788630872bb3b6e561e08da17c111b4a204d5d4be619.png)  


$$\begin{pmatrix}4 & 1 & 0 & 0\\1 & 4 & 1 & 0\\0 & 1 & 4 & 1\\0 & 0 & 1 & 4\end{pmatrix}\begin{pmatrix}y_1''\\y_2''\\y_3''\\y_4''\end{pmatrix}=\frac{6}{h^2}\begin{pmatrix}y_2-2y_1+y_0\\y_3-2y_2+y_1\\y_4-2y_3+y_2\\y_5-2y_4+y_3\end{pmatrix}-\begin{pmatrix}y_0''\\0\\0\\y_4''\end{pmatrix}$$

In [20]:
A = np.asmatrix(linalg.toeplitz([4,1,0,0]))
print(A)

h = 2
y = np.asmatrix(np.arctan(np.arange(0,10+2,2)).reshape(-1,1))
ypp = A.I @ (y[2:,:] - 2*y[1:-1,:] + y[:-2,:]) * 6/h**2

print(ypp)

[[4 1 0 0]
 [1 4 1 0]
 [0 1 4 1]
 [0 0 1 4]]
[[-3.43150627e-01]
 [ 3.98828501e-02]
 [-2.46392138e-02]
 [ 1.19550635e-04]]
